import os
from PIL import Image

src_dir = './python-reference/data/images'
dest_dir = './src/gfx'

os.makedirs(dest_dir, exist_ok=True)

files_to_convert = {
    'hero': f'{src_dir}/characters/hero.png',
    'plain': f'{src_dir}/tiles_nes/plain.png',
    'water': f'{src_dir}/tiles_nes/water.png',
    'forest': f'{src_dir}/tiles_nes/forest.png',
    'mountain': f'{src_dir}/tiles_nes/mountain.png',
    'hill': f'{src_dir}/tiles_nes/hill.png',
    'swamp': f'{src_dir}/tiles_nes/swamp.png',
    'desert': f'{src_dir}/tiles_nes/desert.png',
    'stone': f'{src_dir}/tiles_nes/stone.png',
    'bridge': f'{src_dir}/tiles_nes/bridge.png',
    'chest': f'{src_dir}/decorations_16/chest.png',
}

import glob
for monster_file in glob.glob(f'{src_dir}/monsters/*.png'):
    name = os.path.splitext(os.path.basename(monster_file))[0]
    files_to_convert[name] = monster_file

for name, path in files_to_convert.items():
    if not os.path.exists(path):
        print(f"Warning: {path} not found.")
        continue
        
    img = Image.open(path)
    
    # If it's a spritesheet (like hero.png), grab the first 16x16 frame
    # But only for non-monsters (we don't want to crop the slime unless it's a spritesheet)
    if 'monsters' not in path and (img.width > 16 or img.height > 16):
        img = img.crop((0, 0, 16, 16))
    elif 'monsters' in path and img.width > 32:
        # If it's an animated monster sprite, take first frame (assume 32x32 or similar)
        img = img.crop((0, 0, img.width//2, img.height))
    
    img = img.convert('RGB')
    
    dest_path = f'{dest_dir}/{name}.png'
    img.save(dest_path)
    print(f"Saved {dest_path}")

# Generate convimg.yaml
yaml_content = """palettes:
  - name: global_palette
    images: automatic

converts:
  - name: gfx
    palette: global_palette
    transparent-color-index: 0
    images:
"""

for name in files_to_convert.keys():
    # convimg.yaml includes standard UI sprites not generated by convert_assets.py
    pass

# We actually need to include all PNGs in src/gfx/ into convimg.yaml!
for png_file in glob.glob(f'{dest_dir}/*.png'):
    basename = os.path.basename(png_file)
    yaml_content += f'      - {basename}\n'

yaml_content += """
outputs:
  - type: c
    include-file: gfx.h
    palettes:
      - global_palette
    converts:
      - gfx
"""

with open(f'{dest_dir}/convimg.yaml', 'w') as f:
    f.write(yaml_content)

print("Asset conversion complete.")
