import os
import xml.etree.ElementTree as ET

def main():
    print("Packing levels...")
    
    xml_path = os.path.join(os.path.dirname(__file__), '..', 'python-reference', 'data', 'levels_hero.xml')
    tree = ET.parse(xml_path)
    root = tree.getroot()
    
    levels = []
    
    # We will just parse spells and use the SpellEnum generated by pack_spells.py
    
    for level_node in root.findall('Level'):
        lvl_name = level_node.attrib.get('name')
        xp = int(level_node.attrib.get('xp', 0))
        strength = int(level_node.attrib.get('strength', 0))
        agility = int(level_node.attrib.get('agility', 0))
        hp = int(level_node.attrib.get('hp', 0))
        mp = int(level_node.attrib.get('mp', 0))
        spell = level_node.attrib.get('spell')
        
        spell_enum = "SPELL_NONE"
        if spell:
            safe_spell = "SPELL_" + spell.upper()
            spell_enum = safe_spell
            
        levels.append({
            'level': int(lvl_name),
            'xp': xp,
            'strength': strength,
            'agility': agility,
            'hp': hp,
            'mp': mp,
            'spell': spell_enum
        })
        
    print("Generating src/level_data.h...")
    with open('src/level_data.h', 'w') as f:
        f.write("#ifndef LEVEL_DATA_H\n")
        f.write("#define LEVEL_DATA_H\n\n")
        f.write("#include <stdint.h>\n")
        f.write("#include <stdbool.h>\n")
        f.write("#include \"spell_data.h\"\n\n")
        
        f.write(f"#define NUM_LEVELS {len(levels)}\n\n")
        
        f.write("typedef struct {\n")
        f.write("    uint24_t xpRequired;\n")
        f.write("    uint16_t strength;\n")
        f.write("    uint16_t agility;\n")
        f.write("    uint16_t maxHp;\n")
        f.write("    uint16_t maxMp;\n")
        f.write("    SpellEnum spellId;\n")
        f.write("} LevelDef;\n\n")
        
        f.write("extern const LevelDef levelTable[NUM_LEVELS];\n\n")
        f.write("#endif\n")

    print("Generating src/level_data.c...")
    with open('src/level_data.c', 'w') as f:
        f.write("#include \"level_data.h\"\n\n")
        f.write("const LevelDef levelTable[NUM_LEVELS] = {\n")
        for lvl in levels:
            f.write(f"    {{ {lvl['xp']}, {lvl['strength']}, {lvl['agility']}, {lvl['hp']}, {lvl['mp']}, {lvl['spell']} }},\n")
        f.write("};\n")

if __name__ == "__main__":
    main()
