#include "item_data.h"
#include "action_ids.h"

const ItemDef itemTable[NUM_ITEMS] = {
    {"None", ITEM_TYPE_NONE, 0, 0, 0, 0, false, false},
    {"Hands", ITEM_TYPE_WEAPON, 0, 0, 0, ACTION_USE_ITEM_HANDS, true, false},
    {"Bamboo Pole", ITEM_TYPE_WEAPON, 2, 0, 10, ACTION_USE_ITEM_BAMBOO_POLE, true, false},
    {"Club", ITEM_TYPE_WEAPON, 4, 0, 60, ACTION_USE_ITEM_CLUB, true, false},
    {"Copper Sword", ITEM_TYPE_WEAPON, 10, 0, 180, ACTION_USE_ITEM_COPPER_SWORD, true, false},
    {"Hand Axe", ITEM_TYPE_WEAPON, 15, 0, 560, ACTION_USE_ITEM_HAND_AXE, true, false},
    {"Broad Sword", ITEM_TYPE_WEAPON, 20, 0, 1500, ACTION_USE_ITEM_BROAD_SWORD, true, false},
    {"Flame Sword", ITEM_TYPE_WEAPON, 28, 0, 9800, ACTION_USE_ITEM_FLAME_SWORD, true, false},
    {"Erdrick's Sword", ITEM_TYPE_WEAPON, 40, 0, 2, ACTION_USE_ITEM_ERDRICKS_SWORD, true, false},
    {"Clothes", ITEM_TYPE_ARMOR, 0, 2, 20, 0, true, false},
    {"Leather Armor", ITEM_TYPE_ARMOR, 0, 4, 70, 0, true, false},
    {"Chain Mail", ITEM_TYPE_ARMOR, 0, 10, 300, 0, true, false},
    {"Half Plate", ITEM_TYPE_ARMOR, 0, 16, 1000, 0, true, false},
    {"Full Plate", ITEM_TYPE_ARMOR, 0, 24, 3000, 0, true, false},
    {"Magic Armor", ITEM_TYPE_ARMOR, 0, 24, 7700, 0, true, false},
    {"Erdrick's Armor", ITEM_TYPE_ARMOR, 0, 28, 2, 0, true, false},
    {"Leather Shield", ITEM_TYPE_SHIELD, 0, 4, 90, 0, true, false},
    {"Iron Shield", ITEM_TYPE_SHIELD, 0, 10, 800, 0, true, false},
    {"Silver Shield", ITEM_TYPE_SHIELD, 0, 20, 14800, 0, true, false},
    {"Erdrick's Shield", ITEM_TYPE_SHIELD, 0, 25, 2, 0, true, false},
    {"Dragon's Scale", ITEM_TYPE_TOOL, 0, 2, 20, 0, true, false},
    {"Fairy Water", ITEM_TYPE_TOOL, 0, 0, 38, ACTION_USE_ITEM_FAIRY_WATER, false, false},
    {"Fighter's Ring", ITEM_TYPE_TOOL, 2, 0, 30, 0, true, false},
    {"Herb", ITEM_TYPE_TOOL, 0, 0, 24, ACTION_USE_ITEM_HERB, false, false},
    {"Key", ITEM_TYPE_TOOL, 0, 0, 53, ACTION_USE_ITEM_KEY, false, false},
    {"Key Ring", ITEM_TYPE_TOOL, 0, 0, 1000, ACTION_USE_ITEM_KEY_RING, false, false},
    {"Torch", ITEM_TYPE_TOOL, 0, 0, 8, ACTION_USE_ITEM_TORCH, false, false},
    {"Lantern", ITEM_TYPE_TOOL, 0, 0, 125, ACTION_USE_ITEM_LANTERN, false, false},
    {"Wings", ITEM_TYPE_TOOL, 0, 0, 70, ACTION_USE_ITEM_WINGS, false, false},
    {"Ball of Light", ITEM_TYPE_TOOL, 0, 0, 0, ACTION_USE_ITEM_BALL_OF_LIGHT, false, true},
    {"Fairy Flute", ITEM_TYPE_TOOL, 0, 0, 0, ACTION_USE_ITEM_FAIRY_FLUTE, false, true},
    {"Erdrick's Token", ITEM_TYPE_TOOL, 0, 0, 0, ACTION_USE_ITEM_ERDRICKS_TOKEN, false, true},
    {"Staff of Rain", ITEM_TYPE_TOOL, 0, 0, 0, ACTION_USE_ITEM_STAFF_OF_RAIN, false, true},
    {"Stones of Sunlight", ITEM_TYPE_TOOL, 0, 0, 0, ACTION_USE_ITEM_STONES_OF_SUNLIGHT, false, true},
    {"Rainbow Drop", ITEM_TYPE_TOOL, 0, 0, 0, ACTION_USE_ITEM_RAINBOW_DROP, false, true},
    {"Silver Harp", ITEM_TYPE_TOOL, 0, 0, 0, ACTION_USE_ITEM_SILVER_HARP, false, true},
    {"Gwaelin's Love", ITEM_TYPE_TOOL, 0, 0, 0, ACTION_USE_ITEM_GWAELINS_LOVE, false, true},
    {"Cursed Belt", ITEM_TYPE_TOOL, 0, 0, 180, 0, true, true},
    {"Death Necklace", ITEM_TYPE_TOOL, 0, 0, 1200, 0, true, true},
};
